<!-- ![Alt Text](https://raw.githubusercontent.com/msfasha/307304-Data-Mining/main/images/header.png) -->

<div style="display: flex; justify-content: flex-start; align-items: center;">
   <a href="https://colab.research.google.com/github/msfasha/307307-BI-Methods-Generative-AI/blob/main/20251/Module%203%20-%20Introduction%20to%20Neural%20Networks/2-Neural%20Networks%20Examples.ipynb" target="_parent"><img    
   src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
</div>

## The Perceptron

### Implement the Perceptron Manually

In [ ]:
import numpy as np

# Training data for AND gate
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([0, 0, 0, 1])

# Parameters
w = np.array([0.1, 0.3])   # initial weights
b = 0.2                    # initial bias
eta = 0.1                  # learning rate

# Perceptron training
for epoch in range(100):  # limit to prevent infinite loops
    total_error = 0
    print(f"\nEpoch {epoch + 1}")
    
    for i in range(len(X)):
        x1, x2 = X[i]
        target = y[i]
        
        # Weighted sum
        z = w[0]*x1 + w[1]*x2 + b
        output = 1 if z > 0 else 0
        error = target - output
        
        # Update rule
        w[0] = w[0] + eta * error * x1
        w[1] = w[1] + eta * error * x2
        b = b + eta * error
        
        total_error += abs(error)
        
        # Print details for each record
        print(f"Record {i+1}: x1={x1}, x2={x2}, y={target}")
        print(f"Weighted sum (z) = {z:.2f}, Output = {output}, Error = {error}")
        print(f"Updated weights: w1={w[0]:.2f}, w2={w[1]:.2f}, b={b:.2f}\n")

    # Stop when no errors
    if total_error == 0:
        print("Training complete — no errors remaining.")
        break

print("\nFinal weights:")
print(f"w1 = {w[0]:.2f}, w2 = {w[1]:.2f}, b = {b:.2f}")


### Implement the Perceptron using scikit-learn library

In [4]:
from sklearn.linear_model import Perceptron
import numpy as np

# Training data for AND gate
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

# Initialize and train Perceptron
model = Perceptron(max_iter=100, eta0=0.1, random_state=42)
model.fit(X, y)

# Results
print("Weights:", model.coef_)
print("Bias:", model.intercept_)
print("Predictions:", model.predict(X))

Weights: [[0.2 0.2]]
Bias: [-0.2]
Predictions: [0 0 0 1]


Note: In the scikit-learn Perceptron, the step function (also called the activation function) is a hard threshold function, and it's built-in.<br>

```Python
prediction = 1 if output >= 0 else 0

<div style="text-align: center;">
    <img src="https://raw.githubusercontent.com/msfasha/307307-BI-Methods-Generative-AI/main/images/mlp.png" alt="Simple Perceptron" width="600"/>
</div>

---

## Solving the XOR Problem using a Mulit-Layer Perceptron - MLP

In [1]:
from sklearn.neural_network import MLPClassifier
import numpy as np

# XOR input and output
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

# Define MLP with 1 hidden layer of 2 neurons (minimal config for XOR)
mlp = MLPClassifier(hidden_layer_sizes=(2,), activation='tanh',
                    solver='adam', learning_rate_init=0.01,
                    max_iter=10000, random_state=42)

# Train the model
mlp.fit(X, y)

# Make predictions
predictions = mlp.predict(X)

print("Predictions:\n", predictions)
print("\nWeights (input to hidden):\n", "[ w11 , w12 ]\n[ w21 , w22 ]\n", mlp.coefs_[0])
print("\nBias hidden:\n", mlp.intercepts_[0])
print("\nWeights (hidden to output):\n", mlp.coefs_[1])
print("\nBias output:\n", mlp.intercepts_[1])


Predictions:
 [0 1 1 0]

Weights (input to hidden):
 [ w11 , w12 ]
[ w21 , w22 ]
 [[ 2.7144501   3.27401218]
 [-2.73418453 -3.17014048]]

Bias hidden:
 [ 1.21994174 -1.63451199]

Weights (hidden to output):
 [[-4.37775211]
 [ 4.46553876]]

Bias output:
 [3.61855675]


<div style="text-align: center;">
    <img src="https://raw.githubusercontent.com/msfasha/307307-BI-Methods-Generative-AI/main/images/mlp.png" alt="Multi Layer Perceptron" width="600"/>
</div>

---

## Training a Neural Network to Classify MNIST Dataset
We will use the **Keras library** to easily train a neural network to classify MNIST dataset.

<div style="text-align: center;">
    <img src="https://raw.githubusercontent.com/msfasha/307307-BI-Methods-Generative-AI/main/images/mnist.png" alt="MNIST Dataset" width="600"/>
</div>

In [2]:
from tensorflow import keras
from tensorflow.keras import layers

# 1. Load example data (MNIST digits)
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # normalize to [0,1]

# 2. Build a simple neural network
model = keras.Sequential([
    layers.Flatten(input_shape=(28, 28)),  # flatten 28x28 images
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# 3. Compile and train
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

# 4. Evaluate
print("Evaluating the Model")
model.evaluate(x_test, y_test)

ModuleNotFoundError: No module named 'tensorflow'

---